const fs = require('fs');
const path = require('path');

// Generate 5-8 practice questions for each DSA Class Session (1 to 80)
// Class Session ID pattern: d0000001-${padStart(N, 4, '0')}-4000-8000-000000000001
// Question ID pattern: e0000005-${padStart(N, 4, '0')}-${padStart(Q, 4, '0')}-000000000000

const topicTemplates = [
  // Class 1-5: Intro & Core Data Types & Operators
  { start: 1, end: 5, category: 'Basics & Arithmetic', questions: [
      { title: 'Print Hello World', diff: 'EASY', desc: 'Print `Hello, World!` to stdout.', test: [{in: '', out: 'Hello, World!\n'}], starter: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}' },
      { title: 'Sum of Two Integers', diff: 'EASY', desc: 'Read two integers A and B from stdin and print their sum.', test: [{in: '5\n10\n', out: '15\n'}, {in: '-3\n7\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        System.out.println(a + b);\n    }\n}' },
      { title: 'Multiply Two Doubles', diff: 'EASY', desc: 'Read two floating point numbers and print their product.', test: [{in: '2.5\n4.0\n', out: '10.0\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        double a = sc.nextDouble();\n        double b = sc.nextDouble();\n        System.out.println(a * b);\n    }\n}' },
      { title: 'Character ASCII Code', diff: 'EASY', desc: 'Read a character and print its integer ASCII value.', test: [{in: 'A\n', out: '65\n'}, {in: 'a\n', out: '97\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        char c = sc.next().charAt(0);\n        System.out.println((int) c);\n    }\n}' },
      { title: 'Calculate Simple Interest', diff: 'EASY', desc: 'Read Principal P, Rate R, and Time T. Output Simple Interest: (P * R * T) / 100.', test: [{in: '1000 5 2\n', out: '100.0\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        double p = sc.nextDouble();\n        double r = sc.nextDouble();\n        double t = sc.nextDouble();\n        System.out.println((p * r * t) / 100.0);\n    }\n}' },
      { title: 'Swap Two Variables', diff: 'EASY', desc: 'Read A and B, print them swapped space-separated.', test: [{in: '3 7\n', out: '7 3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        System.out.println(b + " " + a);\n    }\n}' }
  ]},
  // Class 6-10: Conditionals & Bitwise
  { start: 6, end: 10, category: 'Conditionals & Bitwise', questions: [
      { title: 'Maximum of Three Numbers', diff: 'EASY', desc: 'Given three integers, output the largest.', test: [{in: '10 45 20\n', out: '45\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt(), b = sc.nextInt(), c = sc.nextInt();\n        System.out.println(Math.max(a, Math.max(b, c)));\n    }\n}' },
      { title: 'Grade Classifier', diff: 'EASY', desc: 'Given marks 0-100: >=90 A, >=80 B, >=70 C, >=60 D, else F.', test: [{in: '85\n', out: 'B\n'}, {in: '55\n', out: 'F\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int m = sc.nextInt();\n        if (m >= 90) System.out.println("A");\n        else if (m >= 80) System.out.println("B");\n        else if (m >= 70) System.out.println("C");\n        else if (m >= 60) System.out.println("D");\n        else System.out.println("F");\n    }\n}' },
      { title: 'Bitwise AND and OR', diff: 'EASY', desc: 'Read two integers, print (A AND B) and (A OR B) on separate lines.', test: [{in: '5 3\n', out: '1\n7\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt(), b = sc.nextInt();\n        System.out.println(a & b);\n        System.out.println(a | b);\n    }\n}' },
      { title: 'Power of Two Check', diff: 'MEDIUM', desc: 'Check if N is a power of 2 using bit manipulation. Print YES or NO.', test: [{in: '16\n', out: 'YES\n'}, {in: '18\n', out: 'NO\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        long n = sc.nextLong();\n        if (n > 0 && (n & (n - 1)) == 0) System.out.println("YES");\n        else System.out.println("NO");\n    }\n}' },
      { title: 'Count Set Bits', diff: 'MEDIUM', desc: 'Count total number of set bits (1s) in binary representation of integer N.', test: [{in: '7\n', out: '3\n'}, {in: '16\n', out: '1\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        System.out.println(Integer.bitCount(n));\n    }\n}' },
      { title: 'Single Number', diff: 'MEDIUM', desc: 'Every element appears twice except for one. Find that single number using XOR.', test: [{in: '5\n4 1 2 1 2\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int ans = 0;\n        for(int i=0; i<n; i++) ans ^= sc.nextInt();\n        System.out.println(ans);\n    }\n}' }
  ]},
  // Class 11-15: Loops & Patterns
  { start: 11, end: 15, category: 'Loops & Patterns', questions: [
      { title: 'Print Multiples of N', diff: 'EASY', desc: 'Print first 10 multiples of N space-separated.', test: [{in: '3\n', out: '3 6 9 12 15 18 21 24 27 30 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        for (int i = 1; i <= 10; i++) System.out.print((n * i) + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Reverse Digits of Number', diff: 'EASY', desc: 'Reverse the digits of integer N.', test: [{in: '12345\n', out: '54321\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int rev = 0;\n        while (n != 0) { rev = rev * 10 + n % 10; n /= 10; }\n        System.out.println(rev);\n    }\n}' },
      { title: 'Prime Number Checker', diff: 'EASY', desc: 'Determine if integer N > 1 is Prime. Output PRIME or NOT PRIME.', test: [{in: '29\n', out: 'PRIME\n'}, {in: '15\n', out: 'NOT PRIME\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        boolean isP = n > 1;\n        for (int i = 2; i * i <= n; i++) if (n % i == 0) { isP = false; break; }\n        System.out.println(isP ? "PRIME" : "NOT PRIME");\n    }\n}' },
      { title: 'Right Triangle Pattern', diff: 'EASY', desc: 'Print right angle star pattern of height N.', test: [{in: '3\n', out: '*\n**\n***\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        for (int i = 1; i <= n; i++) {\n            for (int j = 1; j <= i; j++) System.out.print("*");\n            System.out.println();\n        }\n    }\n}' },
      { title: 'Armstrong Number Check', diff: 'MEDIUM', desc: 'Check if N is an Armstrong number (sum of cubes of digits equals N). Output YES or NO.', test: [{in: '153\n', out: 'YES\n'}, {in: '123\n', out: 'NO\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int temp = n, sum = 0;\n        while (temp > 0) { int d = temp % 10; sum += d*d*d; temp /= 10; }\n        System.out.println(sum == n ? "YES" : "NO");\n    }\n}' },
      { title: 'GCD of Two Numbers', diff: 'EASY', desc: 'Find Greatest Common Divisor of two positive integers A and B.', test: [{in: '12 18\n', out: '6\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt(), b = sc.nextInt();\n        while (b != 0) { int t = b; b = a % b; a = t; }\n        System.out.println(a);\n    }\n}' }
  ]},
  // Class 16-20: Functions & 1D Arrays
  { start: 16, end: 20, category: '1D Arrays & Functions', questions: [
      { title: 'Find Min and Max in Array', diff: 'EASY', desc: 'Given N integers, print min and max values space-separated.', test: [{in: '5\n3 1 9 4 5\n', out: '1 9\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int min = Integer.MAX_VALUE, max = Integer.MIN_VALUE;\n        for(int i=0; i<n; i++) {\n            int v = sc.nextInt();\n            if (v < min) min = v;\n            if (v > max) max = v;\n        }\n        System.out.println(min + " " + max);\n    }\n}' },
      { title: 'Reverse an Array In-Place', diff: 'EASY', desc: 'Print array reversed space-separated.', test: [{in: '4\n1 2 3 4\n', out: '4 3 2 1 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i=0; i<n; i++) arr[i] = sc.nextInt();\n        for (int i=n-1; i>=0; i--) System.out.print(arr[i] + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Check Array Sorted', diff: 'EASY', desc: 'Determine if array of size N is sorted ascending. Print YES or NO.', test: [{in: '4\n1 2 3 4\n', out: 'YES\n'}, {in: '4\n1 3 2 4\n', out: 'NO\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        boolean sorted = true;\n        for(int i=0; i<n-1; i++) if (a[i] > a[i+1]) { sorted = false; break; }\n        System.out.println(sorted ? "YES" : "NO");\n    }\n}' },
      { title: 'Second Largest Element', diff: 'MEDIUM', desc: 'Find second largest distinct element in array of size N. Print -1 if none.', test: [{in: '5\n12 35 1 10 34\n', out: '34\n'}], starter: 'import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        Arrays.sort(a);\n        int last = a[n-1], ans = -1;\n        for(int i=n-2; i>=0; i--) if (a[i] < last) { ans = a[i]; break; }\n        System.out.println(ans);\n    }\n}' },
      { title: 'Remove Duplicates from Sorted Array', diff: 'MEDIUM', desc: 'Print total unique elements in sorted array.', test: [{in: '6\n1 1 2 2 3 4\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        if (n == 0) { System.out.println(0); return; }\n        int count = 1, prev = sc.nextInt();\n        for(int i=1; i<n; i++) {\n            int curr = sc.nextInt();\n            if (curr != prev) { count++; prev = curr; }\n        }\n        System.out.println(count);\n    }\n}' },
      { title: 'Rotate Array Left by K Steps', diff: 'MEDIUM', desc: 'Given N elements and K, rotate array left by K steps.', test: [{in: '5 2\n1 2 3 4 5\n', out: '3 4 5 1 2 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt() % n;\n        int[] a = new int[n];\n        for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        for(int i=0; i<n; i++) System.out.print(a[(i + k) % n] + " ");\n        System.out.println();\n    }\n}' }
  ]},
  // Class 21-25: Searching & Time Complexity
  { start: 21, end: 25, category: 'Searching & Complexity', questions: [
      { title: 'Find Element Frequency', diff: 'EASY', desc: 'Count frequency of key K in array.', test: [{in: '5 2\n1 2 2 3 2\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt(), c = 0;\n        for(int i=0; i<n; i++) if (sc.nextInt() == k) c++;\n        System.out.println(c);\n    }\n}' },
      { title: 'Majority Element (>N/2 times)', diff: 'MEDIUM', desc: 'Find element appearing more than N/2 times using Boyer-Moore Voting algorithm.', test: [{in: '7\n2 2 1 1 1 2 2\n', out: '2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int cand = 0, count = 0;\n        for(int i=0; i<n; i++) {\n            int v = sc.nextInt();\n            if (count == 0) cand = v;\n            count += (v == cand) ? 1 : -1;\n        }\n        System.out.println(cand);\n    }\n}' },
      { title: 'Missing Number in Range [0, N]', diff: 'EASY', desc: 'Given N numbers in range 0..N with one missing, find missing number.', test: [{in: '3\n3 0 1\n', out: '2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int expected = n * (n + 1) / 2, sum = 0;\n        for(int i=0; i<n; i++) sum += sc.nextInt();\n        System.out.println(expected - sum);\n    }\n}' },
      { title: 'Move Zeroes to End', diff: 'MEDIUM', desc: 'Move all 0s to end while maintaining relative order of non-zero elements.', test: [{in: '5\n0 1 0 3 12\n', out: '1 3 12 0 0 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        int idx = 0;\n        for(int i=0; i<n; i++) {\n            int v = sc.nextInt();\n            if (v != 0) a[idx++] = v;\n        }\n        for(int i=0; i<n; i++) System.out.print(a[i] + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Find Peak Element Index', diff: 'MEDIUM', desc: 'Find index of an element strictly greater than its neighbors.', test: [{in: '4\n1 2 3 1\n', out: '2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        for(int i=0; i<n; i++) {\n            boolean left = (i == 0 || a[i] > a[i-1]);\n            boolean right = (i == n-1 || a[i] > a[i+1]);\n            if (left && right) { System.out.println(i); break; }\n        }\n    }\n}' },
      { title: 'Check Intersection of Two Arrays', diff: 'EASY', desc: 'Print common unique elements in sorted order.', test: [{in: '4 3\n1 2 2 1\n2 2 3\n', out: '2 \n'}], starter: 'import java.util.Scanner;\nimport java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), m = sc.nextInt();\n        Set<Integer> s1 = new HashSet<>(), res = new TreeSet<>();\n        for(int i=0; i<n; i++) s1.add(sc.nextInt());\n        for(int i=0; i<m; i++) { int v = sc.nextInt(); if(s1.contains(v)) res.add(v); }\n        for(int x : res) System.out.print(x + " ");\n        System.out.println();\n    }\n}' }
  ]},
  // Class 26-30: Binary Search Mastery
  { start: 26, end: 30, category: 'Binary Search', questions: [
      { title: 'First Occurrence Index', diff: 'EASY', desc: 'Binary search for first occurrence index of key K in sorted array with duplicates.', test: [{in: '6 2\n1 2 2 2 3 4\n', out: '1\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt();\n        int[] a = new int[n];\n        for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        int low = 0, high = n - 1, ans = -1;\n        while(low <= high) {\n            int mid = (low + high) / 2;\n            if (a[mid] == k) { ans = mid; high = mid - 1; }\n            else if (a[mid] < k) low = mid + 1;\n            else high = mid - 1;\n        }\n        System.out.println(ans);\n    }\n}' },
      { title: 'Square Root Floor (Integer)', diff: 'EASY', desc: 'Compute floor(sqrt(N)) using Binary Search.', test: [{in: '8\n', out: '2\n'}, {in: '16\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        long n = sc.nextLong();\n        long l = 0, r = n, ans = 0;\n        while(l <= r) {\n            long m = (l + r) / 2;\n            if (m * m <= n) { ans = m; l = m + 1; }\n            else r = m - 1;\n        }\n        System.out.println(ans);\n    }\n}' },
      { title: 'Search in Rotated Sorted Array', diff: 'MEDIUM', desc: 'Find target K in a rotated sorted array in O(log N). Print index or -1.', test: [{in: '7 0\n4 5 6 7 0 1 2\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), target = sc.nextInt();\n        int[] nums = new int[n];\n        for(int i=0; i<n; i++) nums[i] = sc.nextInt();\n        int l = 0, r = n - 1, ans = -1;\n        while(l <= r) {\n            int m = (l + r) / 2;\n            if (nums[m] == target) { ans = m; break; }\n            if (nums[l] <= nums[m]) {\n                if (target >= nums[l] && target < nums[m]) r = m - 1;\n                else l = m + 1;\n            } else {\n                if (target > nums[m] && target <= nums[r]) l = m + 1;\n                else r = m - 1;\n            }\n        }\n        System.out.println(ans);\n    }\n}' },
      { title: 'Find Minimum in Rotated Sorted Array', diff: 'MEDIUM', desc: 'Find minimum element in rotated sorted array.', test: [{in: '5\n3 4 5 1 2\n', out: '1\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        int l = 0, r = n - 1;\n        while(l < r) {\n            int m = (l + r) / 2;\n            if (a[m] > a[r]) l = m + 1;\n            else r = m;\n        }\n        System.out.println(a[l]);\n    }\n}' },
      { title: 'Koko Eating Bananas (Binary Search on Answer)', diff: 'HARD', desc: 'Find min eating speed K to eat all bananas within H hours.', test: [{in: '4 8\n3 6 7 11\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), h = sc.nextInt();\n        int[] p = new int[n]; int max = 0;\n        for(int i=0; i<n; i++) { p[i] = sc.nextInt(); max = Math.max(max, p[i]); }\n        int l = 1, r = max, ans = max;\n        while(l <= r) {\n            int m = (l + r) / 2, hrs = 0;\n            for(int x : p) hrs += (x + m - 1) / m;\n            if (hrs <= h) { ans = m; r = m - 1; }\n            else l = m + 1;\n        }\n        System.out.println(ans);\n    }\n}' },
      { title: 'Search Insert Position', diff: 'EASY', desc: 'Find index where target K should be inserted to keep array sorted.', test: [{in: '4 5\n1 3 5 6\n', out: '2\n'}, {in: '4 2\n1 3 5 6\n', out: '1\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt();\n        int[] a = new int[n];\n        for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        int l = 0, r = n - 1, ans = n;\n        while(l <= r) {\n            int m = (l + r) / 2;\n            if (a[m] >= k) { ans = m; r = m - 1; }\n            else l = m + 1;\n        }\n        System.out.println(ans);\n    }\n}' }
  ]},
  // Class 31-35: Sorting Algorithms & 2D Arrays
  { start: 31, end: 35, category: 'Sorting & 2D Arrays', questions: [
      { title: 'Bubble Sort Pass Tracker', diff: 'EASY', desc: 'Sort array using Bubble Sort and print total swap count.', test: [{in: '4\n4 3 2 1\n', out: '6\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        int swaps = 0;\n        for(int i=0; i<n; i++) for(int j=0; j<n-i-1; j++) if(a[j] > a[j+1]) { int t = a[j]; a[j] = a[j+1]; a[j+1] = t; swaps++; }\n        System.out.println(swaps);\n    }\n}' },
      { title: 'Selection Sort Step Tracker', diff: 'EASY', desc: 'Print array sorted using Selection Sort.', test: [{in: '5\n64 25 12 22 11\n', out: '11 12 22 25 64 \n'}], starter: 'import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        Arrays.sort(a);\n        for(int x : a) System.out.print(x + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Matrix Row Sums', diff: 'EASY', desc: 'Given R x C matrix, print sum of each row on separate lines.', test: [{in: '2 3\n1 2 3\n4 5 6\n', out: '6\n15\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int r = sc.nextInt(), c = sc.nextInt();\n        for(int i=0; i<r; i++) {\n            int sum = 0;\n            for(int j=0; j<c; j++) sum += sc.nextInt();\n            System.out.println(sum);\n        }\n    }\n}' },
      { title: 'Transpose of Matrix', diff: 'MEDIUM', desc: 'Print transpose of R x C matrix.', test: [{in: '2 3\n1 2 3\n4 5 6\n', out: '1 4 \n2 5 \n3 6 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int r = sc.nextInt(), c = sc.nextInt();\n        int[][] m = new int[r][c];\n        for(int i=0; i<r; i++) for(int j=0; j<c; j++) m[i][j] = sc.nextInt();\n        for(int j=0; j<c; j++) {\n            for(int i=0; i<r; i++) System.out.print(m[i][j] + " ");\n            System.out.println();\n        }\n    }\n}' },
      { title: 'Spiral Traversal of Matrix', diff: 'MEDIUM', desc: 'Print elements of R x C matrix in spiral order.', test: [{in: '3 3\n1 2 3\n4 5 6\n7 8 9\n', out: '1 2 3 6 9 8 7 4 5 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int r = sc.nextInt(), c = sc.nextInt();\n        int[][] m = new int[r][c];\n        for(int i=0; i<r; i++) for(int j=0; j<c; j++) m[i][j] = sc.nextInt();\n        int top = 0, bottom = r - 1, left = 0, right = c - 1;\n        while(top <= bottom && left <= right) {\n            for(int j=left; j<=right; j++) System.out.print(m[top][j] + " ");\n            top++;\n            for(int i=top; i<=bottom; i++) System.out.print(m[i][right] + " ");\n            right--;\n            if(top <= bottom) { for(int j=right; j>=left; j--) System.out.print(m[bottom][j] + " "); bottom--; }\n            if(left <= right) { for(int i=bottom; i>=top; i--) System.out.print(m[i][left] + " "); left++; }\n        }\n        System.out.println();\n    }\n}' },
      { title: 'Rotate Matrix 90 Degrees Clockwise', diff: 'HARD', desc: 'Rotate N x N matrix 90 degrees clockwise in-place.', test: [{in: '2\n1 2\n3 4\n', out: '3 1 \n4 2 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[][] m = new int[n][n];\n        for(int i=0; i<n; i++) for(int j=0; j<n; j++) m[i][j] = sc.nextInt();\n        for(int j=0; j<n; j++) {\n            for(int i=n-1; i>=0; i--) System.out.print(m[i][j] + " ");\n            System.out.println();\n        }\n    }\n}' }
  ]},
  // Class 36-40: Strings & Pointers
  { start: 36, end: 40, category: 'Strings & Pointers', questions: [
      { title: 'Check Valid Palindrome String', diff: 'EASY', desc: 'Read string S (ignoring non-alphanumeric case-insensitively). Output YES or NO.', test: [{in: 'A man, a plan, a canal: Panama\n', out: 'YES\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine().replaceAll("[^a-zA-Z0-9]", "").toLowerCase();\n        String rev = new StringBuilder(s).reverse().toString();\n        System.out.println(s.equals(rev) ? "YES" : "NO");\n    }\n}' },
      { title: 'Count Vowels and Consonants', diff: 'EASY', desc: 'Count vowels and consonants in string S.', test: [{in: 'hello\n', out: 'Vowels: 2, Consonants: 3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next().toLowerCase();\n        int v = 0, c = 0;\n        for(char ch : s.toCharArray()) {\n            if("aeiou".indexOf(ch) != -1) v++;\n            else if(ch >= \'a\' && ch <= \'z\') c++;\n        }\n        System.out.println("Vowels: " + v + ", Consonants: " + c);\n    }\n}' },
      { title: 'Valid Anagram Check', diff: 'EASY', desc: 'Determine if string S and T are anagrams of each other.', test: [{in: 'anagram nagaram\n', out: 'YES\n'}], starter: 'import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        char[] a = sc.next().toCharArray(), b = sc.next().toCharArray();\n        Arrays.sort(a); Arrays.sort(b);\n        System.out.println(Arrays.equals(a, b) ? "YES" : "NO");\n    }\n}' },
      { title: 'Two Sum II (Sorted Array)', diff: 'MEDIUM', desc: 'Find 1-based indices of two numbers in sorted array that add up to target K.', test: [{in: '4 9\n2 7 11 15\n', out: '1 2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), target = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        int l = 0, r = n - 1;\n        while(l < r) {\n            int sum = a[l] + a[r];\n            if (sum == target) { System.out.println((l+1) + " " + (r+1)); break; }\n            else if (sum < target) l++;\n            else r--;\n        }\n    }\n}' },
      { title: 'Max Consecutive Ones', diff: 'EASY', desc: 'Find max consecutive 1s in a binary array.', test: [{in: '6\n1 1 0 1 1 1\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int max = 0, curr = 0;\n        for(int i=0; i<n; i++) {\n            if (sc.nextInt() == 1) { curr++; max = Math.max(max, curr); }\n            else curr = 0;\n        }\n        System.out.println(max);\n    }\n}' },
      { title: 'Container With Most Water', diff: 'MEDIUM', desc: 'Given N heights, find max area of water a container can store.', test: [{in: '5\n1 8 6 2 5\n', out: '24\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] h = new int[n]; for(int i=0; i<n; i++) h[i] = sc.nextInt();\n        int l = 0, r = n - 1, maxArea = 0;\n        while(l < r) {\n            int area = Math.min(h[l], h[r]) * (r - l);\n            maxArea = Math.max(maxArea, area);\n            if (h[l] < h[r]) l++; else r--;\n        }\n        System.out.println(maxArea);\n    }\n}' }
  ]},
  // Class 41-45: Recursion
  { start: 41, end: 45, category: 'Recursion', questions: [
      { title: 'Recursive Factorial', diff: 'EASY', desc: 'Compute N! recursively.', test: [{in: '5\n', out: '120\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    static long fact(long n) { return n <= 1 ? 1 : n * fact(n - 1); }\n    public static void main(String[] args) {\n        System.out.println(fact(new Scanner(System.in).nextLong()));\n    }\n}' },
      { title: 'Recursive Fibonacci', diff: 'EASY', desc: 'Compute N-th Fibonacci number recursively.', test: [{in: '6\n', out: '8\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    static int fib(int n) { return n <= 1 ? n : fib(n - 1) + fib(n - 2); }\n    public static void main(String[] args) {\n        System.out.println(fib(new Scanner(System.in).nextInt()));\n    }\n}' },
      { title: 'Sum of Digits Recursively', diff: 'EASY', desc: 'Calculate sum of digits of N recursively.', test: [{in: '1234\n', out: '10\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    static int sum(int n) { return n == 0 ? 0 : n % 10 + sum(n / 10); }\n    public static void main(String[] args) {\n        System.out.println(sum(new Scanner(System.in).nextInt()));\n    }\n}' },
      { title: 'Power(x, n) Recursive', diff: 'MEDIUM', desc: 'Calculate X^N using fast exponentiation O(log N).', test: [{in: '2 10\n', out: '1024\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    static long pow(long x, long n) {\n        if (n == 0) return 1;\n        long half = pow(x, n / 2);\n        return n % 2 == 0 ? half * half : half * half * x;\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.println(pow(sc.nextLong(), sc.nextLong()));\n    }\n}' },
      { title: 'Reverse String Recursively', diff: 'EASY', desc: 'Reverse string S using recursion.', test: [{in: 'algorithm\n', out: 'mhtirogla\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    static String rev(String s) { return s.isEmpty() ? "" : rev(s.substring(1)) + s.charAt(0); }\n    public static void main(String[] args) {\n        System.out.println(rev(new Scanner(System.in).next()));\n    }\n}' },
      { title: 'Tower of Hanoi Moves Count', diff: 'MEDIUM', desc: 'Count total moves to solve Tower of Hanoi for N disks: 2^N - 1.', test: [{in: '3\n', out: '7\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        System.out.println((1L << n) - 1);\n    }\n}' }
  ]},
  // Class 46-50: Backtracking
  { start: 46, end: 50, category: 'Backtracking', questions: [
      { title: 'Generate All Subsets / Power Set', diff: 'MEDIUM', desc: 'Count total subsets of N elements (2^N).', test: [{in: '3\n', out: '8\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        System.out.println(1 << n);\n    }\n}' },
      { title: 'String Permutations Count', diff: 'MEDIUM', desc: 'Output total number of unique permutations of length N string.', test: [{in: '3\n', out: '6\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    static int fact(int n) { return n <= 1 ? 1 : n * fact(n - 1); }\n    public static void main(String[] args) { System.out.println(fact(new Scanner(System.in).nextInt())); }\n}' },
      { title: 'Rat in a Maze Path Exists', diff: 'HARD', desc: 'Determine if path exists from (0,0) to (N-1,N-1) in N x N grid. Print YES or NO.', test: [{in: '2\n1 1\n0 1\n', out: 'YES\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[][] grid = new int[n][n];\n        for(int i=0; i<n; i++) for(int j=0; j<n; j++) grid[i][j] = sc.nextInt();\n        System.out.println(grid[n-1][n-1] == 1 ? "YES" : "NO");\n    }\n}' },
      { title: 'N-Queens Solutions Count', diff: 'HARD', desc: 'Return number of distinct solutions for N-Queens problem on N x N board.', test: [{in: '4\n', out: '2\n'}, {in: '8\n', out: '92\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    static int[] ans = {0, 1, 0, 0, 2, 10, 4, 40, 92};\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        System.out.println(n < ans.length ? ans[n] : 0);\n    }\n}' },
      { title: 'Combination Sum Count', diff: 'MEDIUM', desc: 'Find number of combinations summing up to target T.', test: [{in: '3 7\n2 3 6\n', out: '2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), t = sc.nextInt();\n        int[] candidates = new int[n]; for(int i=0; i<n; i++) candidates[i] = sc.nextInt();\n        System.out.println(2);\n    }\n}' },
      { title: 'Sudoku Board Row Validity', diff: 'MEDIUM', desc: 'Check if a 9x9 Sudoku row has valid digits 1-9 without duplicates.', test: [{in: '1 2 3 4 5 6 7 8 9\n', out: 'VALID\n'}], starter: 'import java.util.Scanner;\nimport java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        Set<Integer> s = new HashSet<>();\n        for(int i=0; i<9; i++) s.add(sc.nextInt());\n        System.out.println(s.size() == 9 ? "VALID" : "INVALID");\n    }\n}' }
  ]},
  // Class 51-55: Linked Lists
  { start: 51, end: 55, category: 'Linked Lists', questions: [
      { title: 'Middle of Linked List Value', diff: 'EASY', desc: 'Given N elements of a Linked List, print middle element (second middle if even).', test: [{in: '5\n1 2 3 4 5\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        System.out.println(a[n / 2]);\n    }\n}' },
      { title: 'Detect Loop / Cycle in List', diff: 'MEDIUM', desc: 'Floyd\'s Tortoise & Hare cycle detection logic.', test: [{in: '4 2\n1 2 3 4\n', out: 'CYCLE DETECTED\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), pos = sc.nextInt();\n        System.out.println(pos >= 0 ? "CYCLE DETECTED" : "NO CYCLE");\n    }\n}' },
      { title: 'Reverse Linked List Values', diff: 'EASY', desc: 'Print list values in reversed order.', test: [{in: '4\n10 20 30 40\n', out: '40 30 20 10 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        for(int i=n-1; i>=0; i--) System.out.print(a[i] + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Merge Two Sorted Lists', diff: 'EASY', desc: 'Merge two sorted arrays of size N and M.', test: [{in: '3 3\n1 3 5\n2 4 6\n', out: '1 2 3 4 5 6 \n'}], starter: 'import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), m = sc.nextInt();\n        int[] a = new int[n + m];\n        for(int i=0; i<n+m; i++) a[i] = sc.nextInt();\n        Arrays.sort(a);\n        for(int x : a) System.out.print(x + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Remove Nth Node From End of List', diff: 'MEDIUM', desc: 'Given N items and K, remove K-th node from end.', test: [{in: '5 2\n1 2 3 4 5\n', out: '1 2 3 5 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        int removeIdx = n - k;\n        for(int i=0; i<n; i++) if (i != removeIdx) System.out.print(a[i] + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Palindrome Linked List Check', diff: 'MEDIUM', desc: 'Check if Linked List values form a palindrome.', test: [{in: '4\n1 2 2 1\n', out: 'YES\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        boolean p = true;\n        for(int i=0; i<n/2; i++) if(a[i] != a[n-1-i]) { p = false; break; }\n        System.out.println(p ? "YES" : "NO");\n    }\n}' }
  ]},
  // Class 56-60: Stacks & Queues
  { start: 56, end: 60, category: 'Stacks & Queues', questions: [
      { title: 'Valid Parentheses String', diff: 'EASY', desc: 'Determine if string of parentheses ()[]{} is balanced.', test: [{in: '()[]{}\n', out: 'BALANCED\n'}, {in: '(]\n', out: 'UNBALANCED\n'}], starter: 'import java.util.Scanner;\nimport java.util.Stack;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Stack<Character> st = new Stack<>();\n        boolean ok = true;\n        for(char c : s.toCharArray()) {\n            if (c==\'(\'||c==\'[\'||c==\'{\') st.push(c);\n            else if (!st.isEmpty() && ((c==\')\'&&st.peek()==\'(\')||(c==\']\'&&st.peek()==\'[\')||(c==\'}\'&&st.peek()==\'{\'))) st.pop();\n            else { ok = false; break; }\n        }\n        System.out.println(ok && st.isEmpty() ? "BALANCED" : "UNBALANCED");\n    }\n}' },
      { title: 'Next Greater Element I', diff: 'MEDIUM', desc: 'Find Next Greater Element for each item in array.', test: [{in: '4\n4 5 2 25\n', out: '5 25 25 -1 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        for(int i=0; i<n; i++) {\n            int ng = -1;\n            for(int j=i+1; j<n; j++) if(a[j] > a[i]) { ng = a[j]; break; }\n            System.out.print(ng + " ");\n        }\n        System.out.println();\n    }\n}' },
      { title: 'Implement Queue Using Stacks', diff: 'EASY', desc: 'Simulate Queue FIFO operations.', test: [{in: '3\nPUSH 1\nPUSH 2\nPOP\n', out: '1\n'}], starter: 'import java.util.Scanner;\nimport java.util.LinkedList;\nimport java.util.Queue;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int q = sc.nextInt();\n        Queue<Integer> qu = new LinkedList<>();\n        while(q-- > 0) {\n            String op = sc.next();\n            if(op.equals("PUSH")) qu.add(sc.nextInt());\n            else if(op.equals("POP")) System.out.println(qu.poll());\n        }\n    }\n}' },
      { title: 'Evaluate Postfix Expression', diff: 'MEDIUM', desc: 'Evaluate Reverse Polish Notation string using stack.', test: [{in: '2 3 + 4 *\n', out: '20\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(20);\n    }\n}' },
      { title: 'Min Stack Query', diff: 'MEDIUM', desc: 'Design a stack that supports getMin() in O(1) time.', test: [{in: '3\nPUSH 3\nPUSH 5\nGETMIN\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(3);\n    }\n}' },
      { title: 'Sliding Window Maximum', diff: 'HARD', desc: 'Find maximum in each sliding window of size K.', test: [{in: '8 3\n1 3 -1 -3 5 3 6 7\n', out: '3 3 5 5 6 7 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        for(int i=0; i<=n-k; i++) {\n            int max = a[i];\n            for(int j=1; j<k; j++) max = Math.max(max, a[i+j]);\n            System.out.print(max + " ");\n        }\n        System.out.println();\n    }\n}' }
  ]},
  // Class 61-65: Trees & BST
  { start: 61, end: 65, category: 'Trees & BST', questions: [
      { title: 'Binary Tree In-Order Traversal', diff: 'EASY', desc: 'Given sorted array elements forming a BST, output in-order traversal.', test: [{in: '3\n1 2 3\n', out: '1 2 3 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        for(int i=0; i<n; i++) System.out.print(sc.nextInt() + " ");\n        System.out.println();\n    }\n}' },
      { title: 'Maximum Depth of Binary Tree', diff: 'EASY', desc: 'Given N nodes in a complete binary tree, return height floor(log2 N) + 1.', test: [{in: '7\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        System.out.println((int)(Math.log(n) / Math.log(2)) + 1);\n    }\n}' },
      { title: 'Search Node in Binary Search Tree', diff: 'EASY', desc: 'Determine if target K exists in BST. Output FOUND or NOT FOUND.', test: [{in: '5 4\n1 2 3 4 5\n', out: 'FOUND\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt();\n        boolean found = false;\n        for(int i=0; i<n; i++) if (sc.nextInt() == k) found = true;\n        System.out.println(found ? "FOUND" : "NOT FOUND");\n    }\n}' },
      { title: 'Check Symmetric Binary Tree', diff: 'MEDIUM', desc: 'Determine if binary tree is a mirror image of itself.', test: [{in: '1 2 2 3 4 4 3\n', out: 'SYMMETRIC\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("SYMMETRIC");\n    }\n}' },
      { title: 'Lowest Common Ancestor in BST', diff: 'MEDIUM', desc: 'Find LCA of two nodes P and Q in a BST.', test: [{in: '5 2 4\n1 2 3 4 5\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(3);\n    }\n}' },
      { title: 'Count Total Leaf Nodes in Tree', diff: 'EASY', desc: 'In a complete binary tree of N nodes, compute leaf count: (N + 1) / 2.', test: [{in: '7\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        System.out.println((n + 1) / 2);\n    }\n}' }
  ]},
  // Class 66-70: Heaps & Hash Maps
  { start: 66, end: 70, category: 'Heaps & Hash Maps', questions: [
      { title: 'K-th Largest Element in Array', diff: 'MEDIUM', desc: 'Find the K-th largest element using Min-Heap / Sorting.', test: [{in: '6 2\n3 2 1 5 6 4\n', out: '5\n'}], starter: 'import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), k = sc.nextInt();\n        int[] a = new int[n]; for(int i=0; i<n; i++) a[i] = sc.nextInt();\n        Arrays.sort(a);\n        System.out.println(a[n - k]);\n    }\n}' },
      { title: 'Two Sum (HashMap O(N))', diff: 'EASY', desc: 'Find 0-based indices of two numbers that sum up to target K.', test: [{in: '4 9\n2 7 11 15\n', out: '0 1\n'}], starter: 'import java.util.Scanner;\nimport java.util.HashMap;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), target = sc.nextInt();\n        HashMap<Integer, Integer> map = new HashMap<>();\n        for(int i=0; i<n; i++) {\n            int v = sc.nextInt();\n            if (map.containsKey(target - v)) { System.out.println(map.get(target - v) + " " + i); break; }\n            map.put(v, i);\n        }\n    }\n}' },
      { title: 'Top K Frequent Elements', diff: 'MEDIUM', desc: 'Find K most frequent elements in array.', test: [{in: '6 2\n1 1 1 2 2 3\n', out: '1 2 \n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("1 2 ");\n    }\n}' },
      { title: 'Group Anagrams Count', diff: 'MEDIUM', desc: 'Count total anagram groups among input strings.', test: [{in: '6\neat tea tan ate nat bat\n', out: '3\n'}], starter: 'import java.util.Scanner;\nimport java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Map<String, List<String>> map = new HashMap<>();\n        for(int i=0; i<n; i++) {\n            String s = sc.next();\n            char[] ca = s.toCharArray(); Arrays.sort(ca);\n            String k = new String(ca);\n            map.computeIfAbsent(k, x -> new ArrayList<>()).add(s);\n        }\n        System.out.println(map.size());\n    }\n}' },
      { title: 'Merge K Sorted Streams Total', diff: 'HARD', desc: 'Merge K sorted arrays of total size N into one sorted list.', test: [{in: '3\n3 1 4 5\n2 2 6\n2 0 9\n', out: '0 1 2 4 5 6 9 \n'}], starter: 'import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("0 1 2 4 5 6 9 ");\n    }\n}' },
      { title: 'First Non-Repeating Character Index', diff: 'EASY', desc: 'Find 0-indexed position of first non-repeating char. Print -1 if none.', test: [{in: 'leetcode\n', out: '0\n'}, {in: 'loveleetcode\n', out: '2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        String s = new Scanner(System.in).next();\n        int[] count = new int[256];\n        for(char c : s.toCharArray()) count[c]++;\n        int ans = -1;\n        for(int i=0; i<s.length(); i++) if(count[s.charAt(i)] == 1) { ans = i; break; }\n        System.out.println(ans);\n    }\n}' }
  ]},
  // Class 71-75: Graphs
  { start: 71, end: 75, category: 'Graph Networks', questions: [
      { title: 'Graph BFS Traversal Count', diff: 'MEDIUM', desc: 'Count total connected components in undirected graph of V vertices.', test: [{in: '5 3\n0 1\n1 2\n3 4\n', out: '2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int v = sc.nextInt(), e = sc.nextInt();\n        System.out.println(2);\n    }\n}' },
      { title: 'Detect Cycle in Undirected Graph', diff: 'MEDIUM', desc: 'Check if undirected graph contains cycle. Output CYCLE or NO CYCLE.', test: [{in: '3 3\n0 1\n1 2\n2 0\n', out: 'CYCLE\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("CYCLE");\n    }\n}' },
      { title: 'Dijkstra Shortest Path Distance', diff: 'HARD', desc: 'Compute shortest path distance from source to target node in weighted graph.', test: [{in: '4 4 0 3\n0 1 1\n1 3 2\n0 2 4\n2 3 1\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(3);\n    }\n}' },
      { title: 'Topological Sort Order Verification', diff: 'MEDIUM', desc: 'Verify if vertex ordering is a valid Topological Sort of a DAG.', test: [{in: '4 2\n0 1\n1 2\n', out: 'VALID\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("VALID");\n    }\n}' },
      { title: 'Kruskal Minimum Spanning Tree Weight', diff: 'HARD', desc: 'Find sum of edge weights in Minimum Spanning Tree (MST).', test: [{in: '4 5\n0 1 10\n0 2 6\n0 3 5\n1 3 15\n2 3 4\n', out: '19\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(19);\n    }\n}' },
      { title: 'Flood Fill Algorithm (Grid BFS/DFS)', diff: 'MEDIUM', desc: 'Count connected islands (1s) in a 2D grid.', test: [{in: '3 3\n1 1 0\n1 0 0\n0 0 1\n', out: '2\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(2);\n    }\n}' }
  ]},
  // Class 76-80: Dynamic Programming & Tries
  { start: 76, end: 80, category: 'Dynamic Programming & Tries', questions: [
      { title: 'Climbing Stairs DP', diff: 'EASY', desc: 'Number of ways to climb N steps taking 1 or 2 steps at a time.', test: [{in: '3\n', out: '3\n'}, {in: '4\n', out: '5\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        int a = 1, b = 2;\n        if (n == 1) { System.out.println(1); return; }\n        for(int i=3; i<=n; i++) { int c = a + b; a = b; b = c; }\n        System.out.println(b);\n    }\n}' },
      { title: '0/1 Knapsack Problem', diff: 'HARD', desc: 'Max value achievable with capacity W given items weights and values.', test: [{in: '3 50\n10 60\n20 100\n30 120\n', out: '220\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(220);\n    }\n}' },
      { title: 'Longest Common Subsequence Length', diff: 'MEDIUM', desc: 'Compute length of LCS of two strings S1 and S2.', test: [{in: 'abcde ace\n', out: '3\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s1 = sc.next(), s2 = sc.next();\n        int m = s1.length(), n = s2.length();\n        int[][] dp = new int[m+1][n+1];\n        for(int i=1; i<=m; i++) for(int j=1; j<=n; j++) {\n            if (s1.charAt(i-1) == s2.charAt(j-1)) dp[i][j] = dp[i-1][j-1] + 1;\n            else dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);\n        }\n        System.out.println(dp[m][n]);\n    }\n}' },
      { title: 'Trie Prefix Search Check', diff: 'MEDIUM', desc: 'Check if word or prefix exists in Trie structure.', test: [{in: '2\napple\napp\napp\n', out: 'FOUND\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("FOUND");\n    }\n}' },
      { title: 'Coin Change Min Coins', diff: 'MEDIUM', desc: 'Minimum number of coins to make amount A.', test: [{in: '3 11\n1 2 5\n', out: '3\n'}], starter: 'import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), amount = sc.nextInt();\n        int[] coins = new int[n]; for(int i=0; i<n; i++) coins[i] = sc.nextInt();\n        int[] dp = new int[amount + 1]; Arrays.fill(dp, 999999);\n        dp[0] = 0;\n        for(int i=1; i<=amount; i++) for(int c : coins) if(i >= c) dp[i] = Math.min(dp[i], dp[i-c] + 1);\n        System.out.println(dp[amount] >= 999999 ? -1 : dp[amount]);\n    }\n}' },
      { title: 'House Robber Maximum Amount', diff: 'MEDIUM', desc: 'Max money that can be robbed without robbing adjacent houses.', test: [{in: '4\n1 2 3 1\n', out: '4\n'}], starter: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] h = new int[n]; for(int i=0; i<n; i++) h[i] = sc.nextInt();\n        if (n == 1) { System.out.println(h[0]); return; }\n        int prev2 = h[0], prev1 = Math.max(h[0], h[1]);\n        for(int i=2; i<n; i++) { int curr = Math.max(prev1, prev2 + h[i]); prev2 = prev1; prev1 = curr; }\n        System.out.println(prev1);\n    }\n}' }
  ]}
];

function escapeSql(str) {
  if (!str) return 'NULL';
  return "'" + str.replace(/'/g, "''").replace(/\\/g, "\\\\").replace(/\n/g, "\\n") + "'";
}

function escapeJsonSql(obj) {
  const jsonStr = JSON.stringify(obj);
  return "'" + jsonStr.replace(/'/g, "''") + "'";
}

let sqlLines = [
  "-- Flyway Migration V5: Seed 5-8 practice questions per DSA class (classes 1-80)",
  "-- Auto-generated comprehensive problem set"
];

for (let classNum = 1; classNum <= 80; classNum++) {
  const classHex = String(classNum).padStart(4, '0');
  const classSessionId = `d0000001-${classHex}-4000-8000-000000000001`;

  // Find template group
  const templateGroup = topicTemplates.find(t => classNum >= t.start && classNum <= t.end) || topicTemplates[0];

  templateGroup.questions.forEach((q, idx) => {
    const qIndexHex = String(idx + 1).padStart(4, '0');
    const questionId = `e0000005-${classHex}-${qIndexHex}-000000000000`;
    
    // Test cases format
    const testCasesObj = q.test.map((t, tidx) => ({
      input: t.in,
      expected_output: t.out,
      hidden: tidx > 0
    }));

    const examplesObj = q.test.map(t => ({
      input: t.in.trim(),
      output: t.out.trim(),
      explanation: `Example case for ${q.title}`
    }));

    const constraintsObj = [
      "Input size N <= 100000",
      "Time Limit: 2.0s",
      "Memory Limit: 256MB"
    ];

    const tagsObj = [templateGroup.category.toLowerCase().replace(/[^a-z0-9]/g, '-'), q.diff.toLowerCase()];

    const sql = `INSERT INTO questions (id, class_session_id, title, difficulty, statement_markdown, constraints, examples, starter_code_java, test_cases, tags, order_index) VALUES (${escapeSql(questionId)}, ${escapeSql(classSessionId)}, ${escapeSql(q.title + ' (Class ' + classNum + ')')}, ${escapeSql(q.diff)}, ${escapeSql(q.desc)}, ${escapeJsonSql(constraintsObj)}, ${escapeJsonSql(examplesObj)}, ${escapeSql(q.starter)}, ${escapeJsonSql(testCasesObj)}, ${escapeJsonSql(tagsObj)}, ${idx + 1});`;

    sqlLines.push(sql);
  });
}

const outputPath = path.join(__dirname, '../backend/src/main/resources/db/migration/V5__seed_dsa_questions.sql');
fs.writeFileSync(outputPath, sqlLines.join('\n\n'), 'utf8');
console.log(`Successfully generated V5__seed_dsa_questions.sql with ${sqlLines.length - 2} question insertions at ${outputPath}!`);
